

Name = "bart"
Owner = "clint@getweave.com"
Repo = "weavelab/bart"

[[services]]
Name = "bart-service"
Type = 1 
    [[services.ports]]
    Name = "grpc"
    Protocol = "TCP"
    NodePort = "36011"
    Port = "80"
    TargetPort = "9000"

[[env]]
Name = "LISTEN_PORT"
Type = "value"
Value = "9000"


# [[env]]
# Name = "PASSWORD"
# Secret = "bart-secret"
# Key = "password"

# [[env]]
# Name = "GRPC_PORT"
# ConfigMap = "bart-config"
# Key = "grpc-port"



