# Pipeline TOML config for a deployment in Ploio

Name = "Pull Request"

[[stages]]
Name = "Deploy to Dev"
Type = "deploy"
Cluster = "dev-ut"
Replicas = 1
Strategy = "rolling"
Namespace = "phone"
Memory = "20Mi"
CPU = "20m"

[[stages]]
Name = "Manual Check on Dev"
Type = "check"
Strategy = "manual"
# EmailNotification = true
# SlackNotification = true

[[stages]]
Name = "Production Canary"
Cluster = "dev-ut"
Replicas = 3
Strategy = "canary"
Namespace = "default"
CanaryPercentage = 1
Memory = "30Mi"
CPU = "30m"



