# Pipeline TOML config for a deployment in Ploio

Name = "Pull Request"

[[stages]]
Name = "Deploy to Dev"
Type = "deploy"
Cluster = "dev-ut"
Replicas = 1
Strategy = "rolling"
Namespace = "phone"
Memory = 20
CPU = 20

[[stages]]
Name = "Verify on Dev"
Type = "verify"
EmailNotification = true
SlackNotification = true

[[stages]]
Cluster = "dev-ut"
Replicas = 3
Strategy = "canary"
Namespace = "default"
Memory = 30
CPU = 30
Duration = "10m"
ErrorThreshold = 2
ResponseTimeThreshold = 5


