// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

/*
Package ploioproto is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ApplicationGet
	Application
	Service
	Port
	Env
*/
package ploioproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ApplicationGet struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *ApplicationGet) Reset()                    { *m = ApplicationGet{} }
func (m *ApplicationGet) String() string            { return proto.CompactTextString(m) }
func (*ApplicationGet) ProtoMessage()               {}
func (*ApplicationGet) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

func (m *ApplicationGet) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Application struct {
	ID       string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" gorm:"primary_key"`
	Name     string     `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Owner    string     `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Repo     string     `protobuf:"bytes,4,opt,name=Repo,proto3" json:"Repo,omitempty"`
	Services []*Service `protobuf:"bytes,5,rep,name=Services" json:"Services,omitempty"`
	Env      []*Env     `protobuf:"bytes,6,rep,name=Env" json:"Env,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{1} }

func (m *Application) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Application) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Application) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Application) GetEnv() []*Env {
	if m != nil {
		return m.Env
	}
	return nil
}

type Service struct {
	ID            string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" gorm:"primary_key"`
	Name          string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ApplicationID string  `protobuf:"bytes,3,opt,name=ApplicationID,proto3" json:"ApplicationID,omitempty"`
	Type          string  `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Ports         []*Port `protobuf:"bytes,5,rep,name=Ports" json:"Ports,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{2} }

func (m *Service) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetApplicationID() string {
	if m != nil {
		return m.ApplicationID
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

type Port struct {
	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" gorm:"primary_key"`
	ServiceID  string `protobuf:"bytes,2,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	Protocol   string `protobuf:"bytes,3,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	Port       string `protobuf:"bytes,4,opt,name=Port,proto3" json:"Port,omitempty"`
	TargetPort string `protobuf:"bytes,5,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	NodePort   string `protobuf:"bytes,6,opt,name=NodePort,proto3" json:"NodePort,omitempty"`
}

func (m *Port) Reset()                    { *m = Port{} }
func (m *Port) String() string            { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()               {}
func (*Port) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{3} }

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func (m *Port) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Port) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Port) GetTargetPort() string {
	if m != nil {
		return m.TargetPort
	}
	return ""
}

func (m *Port) GetNodePort() string {
	if m != nil {
		return m.NodePort
	}
	return ""
}

type Env struct {
	ID            string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ApplicationID string `protobuf:"bytes,2,opt,name=ApplicationID,proto3" json:"ApplicationID,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Value         string `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Env) Reset()                    { *m = Env{} }
func (m *Env) String() string            { return proto.CompactTextString(m) }
func (*Env) ProtoMessage()               {}
func (*Env) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{4} }

func (m *Env) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Env) GetApplicationID() string {
	if m != nil {
		return m.ApplicationID
	}
	return ""
}

func (m *Env) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Env) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Env) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplicationGet)(nil), "ploioproto.ApplicationGet")
	proto.RegisterType((*Application)(nil), "ploioproto.Application")
	proto.RegisterType((*Service)(nil), "ploioproto.Service")
	proto.RegisterType((*Port)(nil), "ploioproto.Port")
	proto.RegisterType((*Env)(nil), "ploioproto.Env")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PloioAPI service

type PloioAPIClient interface {
	// rpc ListApplications (ApplicationGet) returns (ApplicationList) {}
	GetApplication(ctx context.Context, in *ApplicationGet, opts ...grpc.CallOption) (*Application, error)
}

type ploioAPIClient struct {
	cc *grpc.ClientConn
}

func NewPloioAPIClient(cc *grpc.ClientConn) PloioAPIClient {
	return &ploioAPIClient{cc}
}

func (c *ploioAPIClient) GetApplication(ctx context.Context, in *ApplicationGet, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/ploioproto.PloioAPI/GetApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PloioAPI service

type PloioAPIServer interface {
	// rpc ListApplications (ApplicationGet) returns (ApplicationList) {}
	GetApplication(context.Context, *ApplicationGet) (*Application, error)
}

func RegisterPloioAPIServer(s *grpc.Server, srv PloioAPIServer) {
	s.RegisterService(&_PloioAPI_serviceDesc, srv)
}

func _PloioAPI_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PloioAPIServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ploioproto.PloioAPI/GetApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PloioAPIServer).GetApplication(ctx, req.(*ApplicationGet))
	}
	return interceptor(ctx, in, info, handler)
}

var _PloioAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ploioproto.PloioAPI",
	HandlerType: (*PloioAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApplication",
			Handler:    _PloioAPI_GetApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptorApi) }

var fileDescriptorApi = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x35, 0x49, 0x53, 0xdb, 0xfb, 0xb0, 0xca, 0xf8, 0xd0, 0x10, 0x44, 0xeb, 0x20, 0x8f, 0x87,
	0x60, 0x0a, 0xcf, 0x9d, 0xbb, 0x4a, 0x4a, 0xc9, 0xa6, 0x86, 0xb4, 0xb8, 0x95, 0x34, 0x8e, 0x31,
	0x98, 0x64, 0x86, 0x31, 0xad, 0xe4, 0x8b, 0xfc, 0x09, 0xf7, 0xfe, 0x85, 0x1f, 0xe1, 0x17, 0xc8,
	0xdc, 0x4c, 0xda, 0xa9, 0x5a, 0x37, 0xee, 0xee, 0xbd, 0xe7, 0xcc, 0xdc, 0x73, 0xce, 0x0c, 0x8c,
	0x53, 0x51, 0x04, 0x42, 0xf2, 0x86, 0x13, 0x10, 0x25, 0x2f, 0x38, 0xd6, 0xfe, 0x8b, 0xbc, 0x68,
	0x3e, 0xee, 0xb6, 0x41, 0xc6, 0xab, 0x59, 0xce, 0x73, 0x3e, 0xc3, 0xf1, 0x76, 0xf7, 0x01, 0x3b,
	0x6c, 0xb0, 0xea, 0x8e, 0xd2, 0x29, 0x4c, 0xe6, 0x42, 0x94, 0x45, 0x96, 0x36, 0x05, 0xaf, 0x97,
	0xac, 0x21, 0x13, 0xb0, 0xa3, 0xd0, 0xb3, 0xa6, 0xd6, 0xf5, 0x38, 0xb1, 0xa3, 0x90, 0x7e, 0xb7,
	0xe0, 0xc2, 0xa0, 0x90, 0xab, 0x23, 0xfe, 0xfa, 0xc1, 0xcf, 0x1f, 0x4f, 0x48, 0xce, 0x65, 0xf5,
	0x8a, 0x0a, 0x59, 0x54, 0xa9, 0x6c, 0xdf, 0x7d, 0x62, 0x2d, 0x55, 0xe7, 0x08, 0x81, 0xc1, 0x2a,
	0xad, 0x98, 0x67, 0xe3, 0x4d, 0x58, 0x93, 0x4b, 0x70, 0xdf, 0x7c, 0xa9, 0x99, 0xf4, 0x1c, 0x1c,
	0x76, 0x8d, 0x62, 0x26, 0x4c, 0x70, 0x6f, 0xd0, 0x31, 0x55, 0x4d, 0x66, 0x30, 0x5a, 0x33, 0xb9,
	0x2f, 0x32, 0xf6, 0xd9, 0x73, 0xa7, 0xce, 0xf5, 0xc5, 0xcd, 0xfd, 0xe0, 0xe8, 0x32, 0xd0, 0x58,
	0x72, 0x20, 0x91, 0xa7, 0xe0, 0x2c, 0xea, 0xbd, 0x37, 0x44, 0xee, 0x5d, 0x93, 0xbb, 0xa8, 0xf7,
	0x89, 0xc2, 0xe8, 0x57, 0x0b, 0x6e, 0x6b, 0xfe, 0x7f, 0xb9, 0x78, 0x06, 0x77, 0x8c, 0x40, 0xa2,
	0x50, 0xbb, 0x39, 0x1d, 0xaa, 0x93, 0x9b, 0x56, 0xb0, 0xde, 0x95, 0xaa, 0xc9, 0x15, 0xb8, 0x31,
	0x97, 0x4d, 0x6f, 0xe9, 0x9e, 0x29, 0x53, 0x01, 0x49, 0x07, 0xd3, 0x6f, 0x16, 0x0c, 0x54, 0x45,
	0x9e, 0xeb, 0xf5, 0xff, 0x16, 0xda, 0xc9, 0x7a, 0x04, 0x63, 0xed, 0x2e, 0x0a, 0xb5, 0xde, 0xe3,
	0x80, 0xf8, 0x30, 0x8a, 0xd5, 0x9e, 0x8c, 0x97, 0x5a, 0xef, 0xa1, 0x57, 0x52, 0xd5, 0xb6, 0x5e,
	0x2a, 0x6e, 0x7e, 0x0c, 0xb0, 0x49, 0x65, 0xce, 0x1a, 0x44, 0x5c, 0x44, 0x8c, 0x89, 0xba, 0x6f,
	0xc5, 0xdf, 0x33, 0x44, 0x87, 0xdd, 0x7d, 0x7d, 0x4f, 0x5b, 0x7c, 0x8b, 0xdf, 0x7f, 0xd2, 0x9f,
	0xb9, 0xd9, 0x67, 0x72, 0x43, 0xcb, 0x8e, 0x91, 0xf8, 0xdf, 0xb2, 0xbc, 0x04, 0xf7, 0x6d, 0x5a,
	0xee, 0x98, 0xd6, 0xd6, 0x35, 0x37, 0x6b, 0x18, 0xc5, 0x2a, 0xd3, 0x79, 0x1c, 0x91, 0x25, 0x4c,
	0x96, 0xac, 0x31, 0xff, 0xae, 0x6f, 0x06, 0x7e, 0xfa, 0xef, 0xfd, 0x87, 0x67, 0x30, 0x7a, 0x6b,
	0x3b, 0xc4, 0xe1, 0xcb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x43, 0x68, 0xb6, 0xfe, 0x73, 0x03,
	0x00, 0x00,
}
